name: listphone
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #  flutter_sticky_header: ^0.6.1
  sticky_grouped_list: ^3.1.0
  permission_handler: ^10.4.0
  url_launcher: ^6.0.11
  image_picker: ^0.8.4
flutter:
  uses-material-design: true
  assets:
    - assets/
